# Generated by Django 3.0.2 on 2020-02-06 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=300)),
                ('p_loc', models.CharField(max_length=300)),
                ('p_det', models.TextField(blank=True)),
                ('p_high', models.TextField(blank=True)),
                ('p_price', models.TextField(blank=True)),
                ('p_app', models.BooleanField(default=False, null=True)),
                ('p_img', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='pckimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_img1', models.FileField(upload_to='media/')),
                ('p_img2', models.FileField(upload_to='media/')),
                ('p_img3', models.FileField(upload_to='media/')),
                ('p_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyse.package')),
            ],
        ),
    ]
