# Generated by Django 3.0.2 on 2020-02-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pckimg',
            options={'verbose_name': 'Package Image', 'verbose_name_plural': 'Package Images'},
        ),
    ]
