# Generated by Django 3.0.2 on 2020-02-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0003_auto_20200207_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.TextField(blank=True, verbose_name='Name')),
                ('s_url', models.TextField(blank=True, verbose_name='Location')),
                ('s_loc', models.TextField(blank=True, verbose_name='Maps URL')),
            ],
            options={
                'verbose_name': 'Package Suggestion',
                'verbose_name_plural': 'Package Suggestions',
            },
        ),
    ]
