# Generated by Django 3.0.2 on 2020-02-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0004_suggest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggest',
            name='s_loc',
        ),
        migrations.AlterField(
            model_name='suggest',
            name='s_url',
            field=models.TextField(blank=True, verbose_name='URL'),
        ),
    ]
