# Generated by Django 3.0.2 on 2020-02-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0005_auto_20200207_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='s_url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
