# Generated by Django 3.0.2 on 2020-02-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0006_auto_20200207_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='s_url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
