# Generated by Django 3.0.2 on 2020-02-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0007_auto_20200213_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='sgts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=300, verbose_name='Name')),
                ('s_url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Package Suggestion',
                'verbose_name_plural': 'Package Suggestions',
            },
        ),
        migrations.DeleteModel(
            name='suggest',
        ),
    ]
