# Generated by Django 3.0.2 on 2020-02-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqs', models.CharField(max_length=100)),
                ('avail', models.BooleanField(null=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.gdet')),
            ],
        ),
    ]
