# Generated by Django 3.0.2 on 2020-02-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='gbook',
        ),
    ]
