# Generated by Django 3.0.2 on 2020-02-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_auto_20200213_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gbook',
            name='reqname',
        ),
        migrations.AddField(
            model_name='gbook',
            name='us',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
