# Generated by Django 3.0.2 on 2020-02-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_auto_20200213_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gbook',
        ),
    ]
