# Generated by Django 3.0.2 on 2020-02-13 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0011_bookguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookguide',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ggg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookguide',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uss', to=settings.AUTH_USER_MODEL),
        ),
    ]
