# Generated by Django 3.0.2 on 2020-02-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200203_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
