# Generated by Django 3.0.2 on 2020-02-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
