# Generated by Django 3.0.2 on 2020-02-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sellprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellprofile',
            name='exp',
        ),
    ]
