# Generated by Django 3.0.2 on 2020-02-07 05:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_sellprofile_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellprofile',
            name='pno',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
