# Generated by Django 3.0.2 on 2020-02-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='app',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
