# Generated by Django 3.0.2 on 2020-02-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_profile_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='app',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
