# Generated by Django 3.0.2 on 2020-02-10 05:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200210_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pno',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.TextField(blank=True),
        ),
    ]
