# Generated by Django 3.0.2 on 2020-02-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200212_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.TextField(blank=True),
        ),
    ]
